### PR TITLE
LOC factor

### PR DESCRIPTION
**Pull request by AsifZaman777**
Minimize the code. rest you memory space

### CODE REVIEW

**Review by AbuJubair7 — COMMENTED** [review]
Your complexity is higher than me **O(n)**.
My complexity is **O(sqrt(n))** which is much faster than this one.

**Comment by AbuJubair7** [comment]
Check the complexity.

**Comment by AsifZaman777** [comment]
Used single loop how the complexity is quadric ?

**Comment by AsifZaman777** [comment]
Check the Complexity

**Comment by AbuJubair7** [comment]
> When an algorithm whose performance is directly proportional to the squared size of the input data set is called Quadratic (O(sqrt(n)))

Example:
```
for i in range(2, int(math.sqrt(n) + 1)):
    // action
```

**Comment by AsifZaman777** [comment]
Got it.

**Pull request closed without merging**
